// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubbzcbknpgtgljwcsmls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InViYnpjYmtucGd0Z2xqd2NzbWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0NTk3MjUsImV4cCI6MjA1MTAzNTcyNX0.ei7llAc_qascT7f4Tf3wZboZmFhPAXEYrqZipShIgSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);